id: 7129e883d4274b5dae03c348965e4ea4
initial_creation_type: ocr
source_metadata:
  volumes:
    191dba2a9d26488e8a27ed9bb56f990e:
      base_file: v063.txt
      image_group_id: I1PD95909
      title: དབུ་མའི་མན་ངག་རིན་པོ་ཆེའི་ཟ་མ་ཏོག་ཁ་ཕྱེ་བ།
      total_pages: 1902
      volume_number: 64
